name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [ created ]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<PYPI_PACKAGE_NAME>
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        shell: bash
        run: |
          pip install --upgrade pip
          pip install poetry twine check-wheel-contents toml argparse

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: "poetry"

      - name: Run Poetry Check for pyproject.toml
        shell: bash
        run: poetry check

      - name: Build Package Distribution
        shell: bash
        run: poetry build

      - name: Check Distribution Descriptions
        shell: bash
        run: |
          twine check dist/*

      - name: Check Wheel Contents
        shell: bash
        run: |
          check-wheel-contents dist/*.whl

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
