name: Check row data updates and create PR if somthing changed
on:
  workflow_dispatch:
    inputs:
      semver_type:
        description: 'Type'
        required: true
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

  schedule:
    - cron: "0 0 * * *"

jobs:
  check_remote_for_change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Public Repository
        uses: actions/checkout@v4
        with:
          repository: countries/countries-data-json
          fetch-depth: 0 # Fetch all branches and tags

      - name: Copy Folder
        run: |
          cp -r data/countries src/country_registry/data
          cp -r data/subdivisions src/country_registry/data
          cp -r data/translations src/country_registry/data
          find src/country_registry/data -type d -empty -delete

      - name: Check for Differences
        id: git_diff
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "has_changes=false" >> $GITHUB_ENV
          fi

      - name: Get current date
        if: env.has_changes == 'true'
        id: date
        run: |
          echo "date::$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "update-raw-data-${{env.date}}"
          base: main
          title: "Update raw data ${{env.date}}"
          body: "This pull request includes updated raw data"
