name: Check row data updates and create PR if somthing changed
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_remote_for_change:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Public Repository
        uses: actions/checkout@v4
        with:
          repository: countries/countries-data-json
          path: 'remote'
          sparse-checkout: 'data/'
          sparse-checkout-cone-mode: false

      - name: Copy remote data
        shell: bash
        run: |
          cp -rf ./remote/data/countries ./src/countries_data/data
          cp -rf ./remote/data/subdivisions ./src/countries_data/data
          cp -rf ./remote/data/translations ./src/countries_data/data
          rm -rf ./remote

      - name: Check for Differences
        id: git_diff
        run: |
          echo $(git status --porcelain)
          if [[ $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "has_changes=false" >> $GITHUB_ENV
          fi


      - name: Get current date
        if: env.has_changes == 'true'
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "update-raw-data-${{env.date}}"
          base: main
          title: "Update raw data ${{env.date}}"
          body: "This pull request includes updated raw data"
